---
- file:
    path: "{{ haproxy_certs_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_cfg_path }}"
    owner: root
    group: root
    mode: "0644"
    validate: "haproxy -c -f %s"
  notify: reload haproxy

- service:
    name: haproxy
    state: started
