version: '3'

services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped

    # NETWORK
    networks:
      - traefik

    # TRAEFIK LABELS
    labels:
      # Enable Traefik for this container
      - "traefik.enable=true"

      # Router definition
      - "traefik.http.routers.whoami.rule=Host(`whoami.example.com`)"
      - "traefik.http.routers.whoami.entrypoints=web"

      # Service definition
      - "traefik.http.services.whoami.loadbalancer.server.port=80"

# NETWORK DEFINITIONS
networks:
  traefik:
    external: true

