---
- file:
    path: "{{ certbot_cloudflare_secrets_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0700"

- template:
    src: cloudflare.ini.j2
    dest: "{{ certbot_cloudflare_ini_path }}"
    owner: root
    group: root
    mode: "0600"
